//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCargo()
        {
            this.tbAreas = new HashSet<tbArea>();
            this.tbDepartamentos = new HashSet<tbDepartamento>();
            this.tbEmpleados = new HashSet<tbEmpleado>();
            this.tbHistorialCargos = new HashSet<tbHistorialCargo>();
        }
    
        public int car_Id { get; set; }
        public string car_Descripcion { get; set; }
        public bool car_Estado { get; set; }
        public string car_RazonInactivo { get; set; }
        public int car_UsuarioCrea { get; set; }
        public System.DateTime car_FechaCrea { get; set; }
        public Nullable<int> car_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> car_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArea> tbAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDepartamento> tbDepartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleado> tbEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistorialCargo> tbHistorialCargos { get; set; }
    }
}
