//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialAmonestacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHistorialAmonestacione()
        {
            this.tbHistorialAmonestaciones1 = new HashSet<tbHistorialAmonestacione>();
        }
    
        public int hamo_Id { get; set; }
        public int emp_Id { get; set; }
        public int tamo_Id { get; set; }
        public System.DateTime hamo_Fecha { get; set; }
        public Nullable<int> hamo_AmonestacionAnterior { get; set; }
        public string hamo_Observacion { get; set; }
        public bool hamo_Estado { get; set; }
        public string hamo_RazonInactivo { get; set; }
        public int hamo_UsuarioCrea { get; set; }
        public System.DateTime hamo_FechaCrea { get; set; }
        public Nullable<int> hamo_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hamo_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistorialAmonestacione> tbHistorialAmonestaciones1 { get; set; }
        public virtual tbHistorialAmonestacione tbHistorialAmonestacione1 { get; set; }
        public virtual tbTipoAmonestacione tbTipoAmonestacione { get; set; }
    }
}
