//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRequisicione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRequisicione()
        {
            this.tbCompetenciasRequisicions = new HashSet<tbCompetenciasRequisicion>();
            this.tbHabilidadesRequisicions = new HashSet<tbHabilidadesRequisicion>();
            this.tbIdiomasRequisicions = new HashSet<tbIdiomasRequisicion>();
            this.tbSeleccionCandidatos = new HashSet<tbSeleccionCandidato>();
            this.tbTitulosRequisicions = new HashSet<tbTitulosRequisicion>();
        }
    
        public int req_Id { get; set; }
        public Nullable<int> req_Edad { get; set; }
        public string req_Experiencia { get; set; }
        public string req_Sexo { get; set; }
        public string req_Descripcion { get; set; }
        public bool req_Estado { get; set; }
        public string req_RazonInactivo { get; set; }
        public string req_Vacantes { get; set; }
        public Nullable<System.DateTime> req_FechaRequisicion { get; set; }
        public Nullable<System.DateTime> req_FechaContratacion { get; set; }
        public int req_UsuarioCrea { get; set; }
        public System.DateTime req_FechaCrea { get; set; }
        public Nullable<int> req_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> req_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompetenciasRequisicion> tbCompetenciasRequisicions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHabilidadesRequisicion> tbHabilidadesRequisicions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIdiomasRequisicion> tbIdiomasRequisicions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSeleccionCandidato> tbSeleccionCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTitulosRequisicion> tbTitulosRequisicions { get; set; }
    }
}
