//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IHSS_RPT
    {
        public int emp_emp_Id { get; set; }
        public Nullable<int> cpla_cpla_IdPlanilla { get; set; }
        public string cpla_DescripcionPlanilla { get; set; }
        public string NombreCompleto { get; set; }
        public string per_Identidad { get; set; }
        public string per_Sexo { get; set; }
        public Nullable<int> per_Edad { get; set; }
        public string per_Direccion { get; set; }
        public string per_Telefono { get; set; }
        public string per_CorreoElectronico { get; set; }
        public string per_EstadoCivil { get; set; }
        public Nullable<decimal> hipa_SueldoNeto { get; set; }
        public Nullable<decimal> CantidadIHSSEmpresa { get; set; }
        public Nullable<decimal> CantidadIHSSColaborador { get; set; }
        public Nullable<decimal> TotalIHSS { get; set; }
        public System.DateTime hipa_FechaPago { get; set; }
        public bool emp_Estado { get; set; }
    }
}
